### ISSUE TITLE
raise ValueError(f"Split name should match '{_split_re}' but got '{split_name}'.")

### ISSUE THREAD

**Issue by AndrewZheng-AI** [explodinggradients/Reward-Model#11]
Traceback (most recent call last):
  File "src/trainer.py", line 66, in train
    train_dataset, validation_dataset = prepare_datasets(config=cfg)
  File "/data_vdb1/nemesis/src/utils.py", line 51, in prepare_datasets
    dataset_list.append(get_single_dataset(name, **kwargs))
  File "/data_vdb1/nemesis/src/utils.py", line 35, in get_single_dataset
    dataset = HFSummary(**kwargs)
  File "/data_vdb1/nemesis/src/dataset.py", line 23, in __init__
    dataset = load_dataset(self.name, "axis", split=self.split)
  File "/usr/local/lib/python3.8/dist-packages/datasets/load.py", line 1810, in load_dataset
    ds = builder_instance.as_dataset(split=split, verification_mode=verification_mode, in_memory=keep_in_memory)
  File "/usr/local/lib/python3.8/dist-packages/datasets/builder.py", line 1124, in as_dataset
    datasets = map_nested(
  File "/usr/local/lib/python3.8/dist-packages/datasets/utils/py_utils.py", line 435, in map_nested
    return function(data_struct)
  File "/usr/local/lib/python3.8/dist-packages/datasets/builder.py", line 1151, in _build_single_dataset
    split = Split(split)
  File "/usr/local/lib/python3.8/dist-packages/datasets/splits.py", line 449, in __new__
    return NamedSplitAll() if name == "all" else NamedSplit(name)
  File "/usr/local/lib/python3.8/dist-packages/datasets/splits.py", line 361, in __init__
    raise ValueError(f"Split name should match '{_split_re}' but got '{split_name}'.")
ValueError: Split name should match '^\w+(\.\w+)*$' but got ''.

anyone meet this problem?

**Comment by liruiluo** [comment]
I also meet this，now have you solved it？
